config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :cards, only: ['index', 'create'] do
    collection do
      delete :destroy_all
    end
  end

  root 'cards#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord

  validates :name, presence: true, uniqueness: true

  def self.search(name_or_rarity)
  	if name_or_rarity.present?
      Card.where("lower(name) = ? or lower(rarity) = ?", name_or_rarity.downcase, name_or_rarity.downcase)
  	else
  	  Card.all
  	end
  end
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
require 'net/http'
require 'net/https'

class CardsController < ApplicationController

  def index
  	@cards = Card.all 
  	@cards = Card.search(params[:search])
  end

  def create
    # get JSON
    result = Net::HTTP.get(URI.parse('https://api.pokemontcg.io/v1/cards'))
    # parse JSON
    json = JSON.parse(result)
    # save data to DB
    json['cards'].each do |data|
      Card.find_or_create_by(
        uid: data['id'],
        name: data['name'],
        imageUrl: data['imageUrl'],
        imageUrlHiRes: data['name'],
        supertype: data['supertype'],
        subtype: data['subtype'],
        number: data['number'],
        rarity: data['rarity'],
        artist: data['artist'],
        series: data['series'],
        set: data['set'],
        setCode: data['setCode'],
        text: data['text']
        )
      end
    redirect_to root_path
  end

  def destroy_all
  	Card.all.delete_all
  	redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pokemons_controller.rb
class PokemonController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pokemon_helper.rb
module PokemonHelper
end

app/views/cards/index.html.erb
<div id='root'>
  <div>
    <nav class="navbar navbar-inverse">
	  <div class="container">
	    <div class="navbar-header">	
		  <%= link_to 'Pokémon TCG', '#', method: 'post', :class => 'navbar-brand' %>
		</div>
		<div id="navbar" class="navbar-collapse collapse">
		  <ul class="nav navbar-nav navbar-right">
		    <li><%= link_to 'Create Backup', cards_path, method: 'post'%></li>
			<li><%= link_to 'Purge Backup', destroy_all_cards_path, method: 'delete' %></li>
		  </ul>
		</div>
	  </div>
    </nav>
    <section class='section'>
      <div class='container'>
        <form class="form-inline">
          <%=form_tag cards_path,{method: 'get', class: 'navbar-form navbar-left', role: 'search'}  do%>
            <div class="form-group">
              <%= text_field_tag :search, params[:search], class: "form-control mr-sm-2", placeholder:"Search by Name/Rarity'"%>
            </div>
            <%= button_tag "Search Backup", :class => 'btn btn-primary', :name => nil %>
          <% end %>
        </form>
        <div class='columns pkmn-gallery fade-in'>
      	  <div class="column">
      	    <% if !@cards.nil? && @cards.count > 0 %>
      	      <h3><%= @cards.count %> Cards Found!</h3>
      	      <% @cards.each do |card| %>
      	  	    <a href=''><%= image_tag("#{card.imageUrl}", class: "hvr-grow") %></a>
      	      <% end %>
      	    <% else %>
      	      <h3>No Cards Found!</h3>
      	    <% end %>
      	  </div>	
        </div>
      </div>
    </section>
  </div>
</div>

app/views/home/index.html.erb
<h1>Hello, Rails!</h1>
<button><%= link_to 'Create Backup', cards_path, method: 'post'  %></button>
<button><%= link_to 'Purge Backup', destroy_all_cards_path, method: 'delete' %></button>
<button><%= link_to 'Search Backup' %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokemonTcg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>